name: publish

on:
  push:
    branches:
      - main

jobs:
  pana:
    timeout-minutes: 9
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} configuration
    strategy:
      matrix:
        package:
          - 'performance'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.5
      - uses: axel-op/dart-package-analyzer@v3
        with:
          relativePath: ${{ matrix.package }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: pana
    timeout-minutes: 4
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} publishing
    strategy:
      matrix:
        package:
          - 'performance'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 2

      - name: Check package Pubspec
        id: pubspec
        run: |
          set +e
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '${{ matrix.package }}/pubspec.yaml' &> /dev/null
          echo ::set-output name=changed::$?
          set -e
      - name: Extract package version
        if: steps.pubspec.outputs.changed == 0
        run: |
          cd ${{ matrix.package }}
          echo "VERSION=$(awk '{if ($1 ~ /^version:/) print $2}' pubspec.yaml)" >> $GITHUB_ENV
      - uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        if: steps.pubspec.outputs.changed == 0
        with:
          package_directory: ${{ matrix.package }}
          credential: ${{ secrets.PUB_CREDENTIALS }}
          flutter_package: true
          skip_test: true
      - name: Create Release
        if: steps.pubspec.outputs.changed == 0
        id: create_release
        uses: softprops/action-gh-release@v0.1.13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.package }}-v${{ env.VERSION }}
          name: ${{ matrix.package }} v${{ env.VERSION }}
          draft: false
          prerelease: false
